### ISSUE TITLE
Sign error when comparing lattice size to point count

### ISSUE THREAD

**Issue by drlight-code** [neka-nat/probreg#57]
I was reading over the supplemental material to your paper and found an inconsistency between the explanation there and the implementation. In the supplemental material it says. "If the variance Σ f is large, N_lattice would be much smaller than N_cloud . On the contrary, N_lattice would be comparable to N_cloud for small variance. Thus, we use full pipeline if N_lattice < αN_cloud, else we omit the Blur stage."
The code, however, reads this:
```
        ph = gf.Permutohedral(fin)
        if ph.get_lattice_size() < n * alpha:
            ph = gf.Permutohedral(fin, False)
```
Whis seems to be the other way around (`with_blur=False` **if** `N_lattice < n*alpha`).

Can you clarify this? Thanks!

**Comment by neka-nat** [comment]
Thank you, that's great!
Your point is correct.
I've pushed the fixed version to master branch.

**Comment by Sunzhiliang** [comment]
In my opinion, “ ph = gf.Permutohedral(fin)”  is enough for this  Python implement， 
in the origin paper, the aim to compute "ph = gf.Permutohedral(fin, False)" is to improve efficiency, while not accuracy.
However the “ph”  may be computed twice，increase running time.

**Comment by drlight-code** [comment]
@Sunzhiliang is there a way to get the resulting lattice size without having to run the actual initialization in order to still get an  efficiency improvement? Or would you say that this doesn't pay off here?

**Comment by Sunzhiliang** [comment]
@drlight-code the origin c++ implement  is efficient to deal it, the Python improvement here is a black box

**Comment by drlight-code** [comment]
Could you provide a link to the original implementation?

**Comment by neka-nat** [comment]
Hi,
The calculation of blur is eliminated in the `ph.filter` function, so in some cases the calculation is reduced.
However, there is almost no effect, so it can be removed.

The original implementation is [here](https://bitbucket.org/gaowei19951004/poser/src/master/).
